GET  http://localhost:5076/records

###
GET  http://localhost:5076/records/2


###
POST http://localhost:5076/records
Content-Type: application/json

{
  "name": "Sixth",
  "genreId": 2,
  "price": 20,
  "releaseDate": "2007-02-02"
}


###
PUT http://localhost:5076/records/1
Content-Type: application/json

{
  "name": "First",
  "genreId":6,
  "price": 15.99,
  "releaseDate": "2004-02-02"
}

###
DELETE http://localhost:5076/records/3